id: I86AD3711
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:08:22+00:00'
last_modified: '2022-06-08T09:37:34.866389+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ34261
  title: གསུང་འབུམ། བསྟན་དར་ལྷ་རམས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5A53:
      image_group_id: I4CZ45290
      title: ''
      total_pages: 484
      order: 1
      base_file: 5A53.txt
    2F05:
      image_group_id: I4CZ45291
      title: ''
      total_pages: 467
      order: 2
      base_file: 2F05.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
